cc_binary(
    name = "shttps",
    srcs = ["shttps.cpp"],
    deps = [
        "//lib:shttps-lib",
        "@curl//:curl-lib",
        "@jansson//:jansson-lib",
        "@lua//:lua-lib",
        "@openssl//:openssl-lib",
    ],
)
